class ElementTypes {
  // Éléments standard pour toutes les sections
  static const List<String> standard = [
    'MUR EST', 'MUR NORD', 'MUR OUEST', 'MUR SUD', 'PAPIER PEINT', 'CARRELAGE',
    'CLOISON', 'TAPISSERIE', 'LÉ DE PAPIER PEINT', 'ISOLATION', 'LUMINAIRE',
    'FAUX PLAFOND', 'PLINTHES', 'PLINTHES CARRELÉES', 'GOULOTTE', 'PORTE',
    'PORTE ISOPLANE', 'MOULURES', 'PLAQUE DE PROPRETÉ', 'POIGNÉE LAITON',
    'SERRURE', 'GONDS', 'CHAMBRANLE', 'VERROU', 'PAUMELLE', 'HUISSERIES',
    'VITRAGE', 'AÉRATION', 'TRINGLE', 'RIDEAU', 'GARDE-CORPS', 'VOLET ROULANT',
    'BATTANT', 'PUITS DE LUMIÈRE', 'VELUX', 'LUCARNE', 'STORE',
    'FENÊTRE SIMPLE VANTAIL', 'FENÊTRE DOUBLE VANTAUX', 'PRISES ÉLECTRIQUES',
    'INTERRUPTEURS', 'PRISE TÉLÉVISION', 'PRISE TÉLÉPHONE', 'PRISE RÉSEAU',
    'BOÎTE DE DÉRIVATION', 'SORTIE DE FIL', 'VMC', 'PLACARD ÉLECTRIQUE',
    'DISJONCTEUR DIFFÉRENTIEL', 'COUPE-CIRCUIT', 'COMPTEUR', 'GLOBE', 'LED',
    'NÉON', 'AMPOULE', 'DOUILLE', 'LUSTRE', 'SPOT', 'LINOLITE', 'SUSPENSION',
    'LAMPE', 'ABAT-JOUR', 'TUYAUTERIE', 'GAINE', 'DESCENTE', 'CONDUITE',
    'CUMULUS', 'RADIATEUR', 'CONVECTEUR'
  ];

  // Éléments spécifiques par section
  static const Map<String, List<String>> sectionSpecific = {
    'EXTÉRIEUR': [
      'PORTAIL', 'PORTILLON', 'BOÎTE AUX LETTRES', 'VERROU', 'PILIER', 'CLÔTURE',
      'CLÔTURE GRILLAGÉE', 'ESPALIER', 'PILASTRE', 'CHAPERON', 'TUILES', 'CLAUSTRA',
      'HAIE VIVE', 'SEUIL EN PIERRES', 'SEUIL EN BÉTON', 'ALLÉE GRAVILLONNÉE',
      'ALLÉE EN PIERRES', 'PISCINE', 'PISCINE COQUE POLYESTER', 'GELCOAT', 'LINER',
      'SKIMMER', 'POOL HOUSE', 'TOIT', 'TUILES CANAL', 'TUILES MÉCANIQUES', 'TÔLE',
      'RÂTEAU HERTZIEN', 'GOUTTIÈRE', 'SOLIN', 'ZINGUERIE', 'TERRE-PLEIN', 'ÎLOT',
      'PARTERRE', 'MASSIF', 'PLATE-BANDE', 'TERRASSE', 'TERRASSON', 'DALLES SUR PLOTS',
      'INTERPHONE', 'SONNETTE', 'CARILLON', 'VISIOPHONE'
    ],
    'JARDIN': [
      'TERRE-PLEIN', 'ÎLOT', 'PARTERRE', 'MASSIF', 'PLATE-BANDE', 'TERRASSE',
      'TERRASSON', 'DALLES SUR PLOTS', 'PORTAIL', 'PORTILLON', 'BOÎTE AUX LETTRES',
      'VERROU', 'PILIER', 'CLÔTURE', 'CLÔTURE GRILLAGÉE', 'ESPALIER', 'PILASTRE',
      'CHAPERON', 'TUILES', 'CLAUSTRA', 'HAIE VIVE', 'SEUIL EN PIERRES',
      'SEUIL EN BÉTON', 'ALLÉE GRAVILLONNÉE', 'ALLÉE EN PIERRES', 'PISCINE',
      'PISCINE COQUE POLYESTER', 'GELCOAT', 'LINER', 'SKIMMER', 'POOL HOUSE',
      'TOIT', 'TUILES CANAL', 'TUILES MÉCANIQUES', 'TÔLE', 'RÂTEAU HERTZIEN',
      'GOUTTIÈRE', 'SOLIN', 'ZINGUERIE', 'INTERPHONE', 'SONNETTE', 'CARILLON', 'VISIOPHONE'
    ],
    'DRESSING': [
      'PLACARD', 'DRESSING', 'ÉTAGÈRE', 'TRINGLERIE', 'PENDERIE', 'TIROIR', 'CAISSON'
    ],
    'CUISINE': [
      'PLAQUE DE CUISSON VITROCÉRAMIQUE', 'CUISINIÈRE À GAZ', 'FOUR', 'GRILLE',
      'PLAQUE', 'LÈCHEFRITE', 'RÉFRIGÉRATEUR', 'CLAYETTE', 'CONTRE-PORTE',
      'MEUBLE FORMICA', 'MEUBLE MÉLAMINÉ', 'ÉTAGÈRE', 'HOTTE ASPIRANTE',
      'ÉVIER RÉSINE', 'ÉVIER ÉMAIL', 'ÉVIER INOX', 'BAC', 'ÉGOUTTOIR',
      'BONDE DE FOND', 'MITIGEUR', 'MÉLANGEUR', 'MOBILIER', 'VAISSELLE',
      'COUVERT', 'LAVE-VAISSELLE'
    ],
    'SALON': [
      'PARQUET FLOTTANT', 'DALFLEX', 'GERFLEX', 'CHEMINÉE', 'CHEMINÉE EN MARBRE',
      'INSERT', 'JAMBAGE', 'FOYER', 'CANAPÉ SKAÏ', 'CANAPÉ CUIR', 'CANAPÉ SIMILICUIR',
      'TÉLÉVISEUR CATHODIQUE', 'LCD', 'ÉCRAN PLAT', 'BIBELOTS', 'BAR'
    ],
    'SALLE À MANGER': [
      'PARQUET FLOTTANT', 'DALFLEX', 'GERFLEX', 'CHEMINÉE', 'CHEMINÉE EN MARBRE',
      'INSERT', 'JAMBAGE', 'FOYER', 'CANAPÉ SKAÏ', 'CANAPÉ CUIR', 'CANAPÉ SIMILICUIR',
      'TÉLÉVISEUR CATHODIQUE', 'LCD', 'ÉCRAN PLAT', 'BIBELOTS', 'BAR'
    ],
    'SÉJOUR': [
      'PARQUET FLOTTANT', 'DALFLEX', 'GERFLEX', 'CHEMINÉE', 'CHEMINÉE EN MARBRE',
      'INSERT', 'JAMBAGE', 'FOYER', 'CANAPÉ SKAÏ', 'CANAPÉ CUIR', 'CANAPÉ SIMILICUIR',
      'TÉLÉVISEUR CATHODIQUE', 'LCD', 'ÉCRAN PLAT', 'BIBELOTS', 'BAR'
    ],
    'SALLE DE BAINS': [
      'MEUBLE FORMICA', 'MEUBLE MÉLAMINÉ', 'TIROIR', 'ÉTAGÈRE', 'MIROIR',
      'CIEL DE MIROIR', 'SPOTS D\'ÉCLAIRAGE', 'NÉON', 'LAVABO PORCELAINE',
      'LAVABO ÉMAIL', 'VASQUE', 'COLONNE', 'BONDE DE FOND', 'MITIGEUR',
      'MÉLANGEUR', 'BAIGNOIRE', 'PORCELAINE', 'BAIGNOIRE ÉMAIL', 'ACRYLIQUE',
      'JUPE DE LAVABO', 'SIPHON', 'INVERSEUR', 'JOINT PÉRIPHÉRIQUE', 'DOUCHETTE',
      'FLEXIBLE', 'PORTE-SAVON', 'DOUCHE À L\'ITALIENNE', 'TOTEM', 'POMME',
      'POMMEAU', 'SÈCHE-SERVIETTES'
    ],
    'TOILETTES': [
      'DÉVIDOIR', 'WC PORCELAINE', 'ÉMAIL', 'CUVETTE D\'AISANCES', 'CHASSE D\'EAU',
      'CHASSE DORSALE', 'POUSSOIR', 'LUNETTE', 'ROBINET DE COUPURE', 'SANIBROYEUR'
    ],
    'BUANDERIE': [
      'CHAUDIÈRE', 'CHAUFFAGE PAC', 'CHAUFFAGE CENTRAL', 'LAVE-LINGE', 'SÈCHE-LINGE'
    ],
    'CHAMBRE 1': [
      'TÊTE DE LIT', 'SOMMIER', 'MATELAS', 'TABLE DE NUIT'
    ],
    'CHAMBRE 2': [
      'TÊTE DE LIT', 'SOMMIER', 'MATELAS', 'TABLE DE NUIT'
    ],
    'ESCALIER': [
      'VOLÉE', 'PALIER', 'RAMBARDE', 'RAMPE', 'MARCHE', 'CONTREMARCHE',
      'NEZ-DE-MARCHE', 'CAGE D\'ESCALIER', 'MAIN-COURANTE', 'QUART-TOURNANT'
    ],
    'CAVE': [
      'SOUPIRAIL', 'ÉTAGÈRE MÉTALLIQUE', 'RAYONNAGE'
    ]
  };

  // Méthode pour obtenir tous les éléments pour une section spécifique
  static List<String> getElementsForSection(String sectionName) {
    List<String> sectionElements = sectionSpecific[sectionName] ?? [];
    // Combine les éléments spécifiques avec les éléments standard
    return [...sectionElements, ...standard];
  }
}